language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --release --verbose
  - cargo test --release --verbose --features racket
  - cargo doc
