language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build   --verbose
  - cargo test    --verbose --release
  - cargo rustdoc --verbose -- --html-in-header rustdoc-include-katex-header.html
matrix:
  fast_failures: true
  include:
    - rust: nightly-2018-05-04
      env:
        - CLIPPY_VERSION=0.0.196
      before_script:
        - rustup component add rustfmt-preview
        - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
      script:
        - cargo fmt --all -- --write-mode=diff
        - cargo clippy || echo "clippy failure disregarded (see rust-clippy#2594)"
