[package]
name = "programinduction"
version = "0.1.0"
authors = ["Lucas Morales <lucas@lucasem.com>"]

[dependencies]
itertools = "0.7"
nom = "4.0.0-beta1"
polytype = "1.2"
rand = "0.4"
rayon = "1.0"
workerpool = "1.1"

[features]
default = ["racket"]
racket = []
