[package]
name = "programinduction"
version = "0.2.3"
authors = ["Lucas Morales <lucas@lucasem.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/lucasem/program-induction"
homepage = "https://github.com/lucasem/program-induction"
documentation = "https://docs.rs/programinduction"
description = "A library for program induction and learning representations."
keywords = ["language", "inference", "bayesian", "genetic", "learning"]
categories = ["algorithms", "science"]

[dependencies]
crossbeam-channel = "0.1"
itertools = "0.7"
lazy_static = "1.0"
nom = "4.0.0-beta2"
num_cpus = "1.8"
polytype = "2.1"
rand = "0.4"
rayon = "1.0"
workerpool = "1.1"

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[features]
racket = []
par_enum = []
